#spring:
#  #-----------------------------------------------------------------
#  ##                        Redis 连接配置                         --
#  #-----------------------------------------------------------------
#  data:
#    redis:
#      host: ip
#      port: ${REDIS_PORT:6379}
#      password: ${REDIS_PASSWORD:password}
#      database: ${REDIS_DATABASE:15}
#####################################################################
###                         Jet-cache 配置                          ##
#####################################################################
#jetcache:
#  #统计间隔，0表示不统计
#  statIntervalMinutes: 15
#  areaInCacheName: false
#  local:
#    default:
#      type: linkedhashmap
#      keyConvertor: fastjson
#  remote:
#    default:
#      type: redis
#      keyConvertor: fastjson
#      valueEncoder: java
#      valueDecoder: java
#      poolConfig:
#        minIdle: 5
#        maxIdle: 20
#        maxTotal: 50
#      host: ip
#      port: ${REDIS_PORT:6379}
#      password: ${REDIS_PASSWORD:password}
#      database: ${REDIS_DATABASE:15}
spring:
  application:
    name: custom_jetcache_framework
    port: 8080
  #redistemplate
  data:
    redis:
      host: 192.168.18.100
      port: 6379
      database: 0
jetcache:
  #统计间隔，0表示不统计
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 192.168.18.100
      port: 6379

